### ISSUE TITLE
Mapping files from "__UNKNOWN" folder

### ISSUE THREAD

**Issue by ilyabru** [TombRaiderModding/ModLoader#1]
Hi, when unpacking TR7, the bigfile unpacker creates a folder called "__UNKNOWN" next to the pc-w folder. I've been able to map files from pc-w to the mods folder but not this one. Is it even possible?

For example, how would I map this file: "<bigfile_unpacked_path>\FFFFFFE1\\__UNKNOWN\unknown\2BDBA398.unknown" to the mods folder?

**Comment by TheIndra55** [comment]
The "__UNKNOWN" folder is not actually a path used by the game, it's a folder used by your unpacker to put files with an unknown hash. The actual file name of `2BDBA398.unknown` is `\sndstrm\vo\alister\i_alst_hint_01_04.mul`, you can download an updated file-list [here](https://cdcengine.re/hashdb/projects/6/filelist).

I also suggest using [Yura](https://tombraidermodding.com/guide/yura) to extract files from your Bigfile since it's newer and comes with updated file lists.

**Comment by ilyabru** [comment]
Thank you! That was the issue all along, I've updated the file list and now the files are in the right place. Closing issue.

Also, thanks for making this tool, it made modding way easier.
